### ISSUE TITLE
Standby power consumption

### ISSUE THREAD

**Issue by sid548** [Savjee/home-energy-monitor#33]
Hello,
I am going through the project but one thing still I am not able to understand is about the standby power consumption (Always -ON)
. What is the purpose of calculating it and how is it being calculated ?

It would be great if you can give me a hint about that .

Thanks

**Comment by Savjee** [comment]
Standby power is the minimum amount of power that your house consumes with appliances that are always on. That's the consumption of: fridges, freezers, standby devices, always plugged-in chargers, etc...

It's being calculated here: https://github.com/Savjee/home-energy-monitor/blob/master/src-aws/functions/graphql/resolvers/stats.js#L20

It basically is the "mode" of the dataset. -> The lowest, most frequently seen value in the set.
That's probably not the correct way of calculating it, but it's close enough.

Hope that helps.

**Comment by sid548** [comment]
Thanks a lot

**Comment by Savjee** [comment]
Going to close this issue now. But let me know if you have additional questions ;)
