### ISSUE TITLE
New library dependency.

### ISSUE THREAD

**Issue by Pigi-102** [Savjee/home-energy-monitor#34]
Hi, while building the actual project I get the following error:
Compiling .pio/build/esp32doit-devkit-v1/libd11/Adafruit GFX Library/Adafruit_GrayOLED.cpp.o
In file included from .pio/libdeps/esp32doit-devkit-v1/Adafruit GFX Library/Adafruit_GrayOLED.cpp:20:0:
.pio/libdeps/esp32doit-devkit-v1/Adafruit GFX Library/Adafruit_GrayOLED.h:30:32: fatal error: Adafruit_I2CDevice.h: No such file or directory

which is easy solved by adding the following lib in lib_deps ( platformio.ini )
 Adafruit BusIO

which  download the needed library and build successful.

Maybe Adafruit chenge some libraries ?

Can you check, please ?

**Comment by gui28347** [comment]
in the Visual Studio console, inside Platform IO tab, type: pio lib install "adafruit/Adafruit BusIO"
Try to build again. It fixed for me.

**Comment by Pigi-102** [comment]
It works. My was an advice to change the lb_deps for future builders :)

**Comment by Savjee** [comment]
Thanks for reporting!
This should fix it: https://github.com/Savjee/home-energy-monitor/commit/89459bdbf09d7d8a87625a5cc038a2ec748fad95

Can you check and confirm? Reopen the issue if it's not working.
