### ISSUE TITLE
Strange behaviour: ESP32 serial monitor shows MQTT msg sent but AWS IOT never receives the same

### ISSUE THREAD

**Issue by adukale** [Savjee/home-energy-monitor#50]
Hi
Finally decided to ditch the esp8266 and move to esp32. Made necessory modifications and uploaded code on ESP32.
AWS IOT registers the device, esp32 shows MQTT msg sent in serial monitor but the message is never recived on AWS iot.
No rules executed, nothing. Tried changing the rule, also tried the test menu from AWS IOT to subscribe to "#" i.e. all topics, here also the result is same. No message received.
Also, in thing's activity menu I can see the device was connected but in next 10 seconds the device was disconnecting, this behavior was consistant.

![image](https://user-images.githubusercontent.com/1003980/119239866-ab9bb280-bb69-11eb-95a0-4ececbdb18f4.png)

The serial monitor shows: AWS publish then AWS Connecting. Is this normal?
![image](https://user-images.githubusercontent.com/1003980/119239892-eef62100-bb69-11eb-9e95-8afd845c2c14.png)

**Comment by Savjee** [comment]
It's not normal that it has to reconnect after sending a message. Looks like a permission issue. When the ESP32's certificate is not allowed to publish to a certain topic, the broker will disconnect you.

Try enabling IoT Core logging and check CloudWatch for additional details:
https://docs.aws.amazon.com/iot/latest/developerguide/configure-logging.html#configure-logging-console

**Comment by adukale** [comment]
@Savjee Thank you for the quick response. Checking with this.
Just a query, how should be the certificate & keys in certificates directory? As it is or do I need to enclose the lines in " - " \?

**Comment by Savjee** [comment]
As it is, no changes needed.

**Comment by adukale** [comment]
@Savjee Thank you for pointing me in the right direction.
Don't know what was the exact issue but I have managed to get the esp32 up and running after fiddling with policies & certificates.
Thank You for the Awesome Project.

**Comment by Savjee** [comment]
Nice! AWS IoT Policies are indeed a nightmare to configure correctly. Hard to debug as well.
