### ISSUE TITLE
[RFE] [HASS] config item to switch between sensor autoconfig or manual config.

### ISSUE THREAD

**Issue by Pigi-102** [Savjee/home-energy-monitor#58]
When I restart homeassistant for, say , a configuration change or whatever reason the sensor remain in entity not available for quite a long time.
I use mosquitto as broker and all my other sensor ( not "autoconfigured" ) start sending data to broker and get sent to HASS as soon as the HASS itself is up and running.
The only one that remains in "Entity not available" is your ( wonderful ) sensor.
From the mosquitto log I can see that my ESP32 send the message :
1628280703: Received PUBLISH from IoTEnMon (d0, q0, r0, m0, 'homeassistant/sensor/IoTEnMon/state', ... (14 bytes))
but being that HASS does not have a configuration for it, mosqutto don't forward it to HASS.
After some time ( 10 minutes or more ) the ESP32 send the config message:
1628281285: Received PUBLISH from IoTEnMon (d0, q0, r0, m0, 'homeassistant/sensor/IoTEnMon/config', ... (318 bytes))
and from this moment everything works as expected.
Is it possible to have some config item to choice between autoconfig and manually config ?

**Comment by Savjee** [comment]
Normally we send a discovery message to Home Assistant every 15 minutes. So it should only take 15minutes at most to get your sensor back in HA.

That FreeRTOS task is defined here:
https://github.com/Savjee/home-energy-monitor/blob/70fd234b305f2d3f8040fb9a9ef743cf9b9b6e74/src-esp32/src/tasks/mqtt-home-assistant.h#L77

You could run this task more frequently, or trigger it when the MQTT connection is first established.

Not sure if there's another way around this. Maybe define an empty template sensor in HA? Not sure if MQTT could then update it though.
