### ISSUE TITLE
Add multiple sensors

### ISSUE THREAD

**Issue by KillahB33** [Savjee/home-energy-monitor#63]
Is this possible to use one of the other inputs on the ESP32 to add another sensor? 
I am going to set this up in my main panel and wanted to track a few other things.

**Comment by Savjee** [comment]
Yes that's possible by creating more instances of Emonlib.
Unfortunately this is not something I can work on. Happy to accept pull requests though ;)

**Comment by KillahB33** [comment]
Deal, I'll see if I can make that happen. Thanks for pointing me in the right direction!
