### ISSUE TITLE
Direct CT Connection

### ISSUE THREAD

**Issue by JuandreG** [Savjee/home-energy-monitor#66]
Hello.

Is it possible to connect the SCT013 directly to the ESP32 board and measure amps? You mention that your initial thought was to cut it off and connect the wires directly to the ESP32 board, I would like to do this but I don't know where to connect the wires on the board.

If you could please guide me in connecting these wires on the board directly it would be greatly appreciated.

Regards and awesome project.

**Comment by Savjee** [comment]
Hi,

Yes you can connect it directly to the ESP32. It's the exact same wiring. Same pins as you would use for the headphone jack.
