### ISSUE TITLE
Will this work with your code

### ISSUE THREAD

**Issue by steveuk23** [Savjee/home-energy-monitor#67]
Hi I love your project and am wondering do you think this ready made board will work with your code. 
I prefer the idea of WiFi & MQTT reconnecting that your have on yours.
This guy makes boards on eBay but recommends his code.
Thanks
[https://www.ebay.co.uk/itm/ESP8266-Mains-Current-Sensor-Wemos-Current-transformer-SCT013-100A-50mA-/133077015640?mkcid=16&mkevt=1&_trksid=p2349624.m46890.l49286&mkrid=710-127635-2958-0](Ebay)

**Comment by Savjee** [comment]
It seems compatible yes. The only things that might change are pin numbers.
