### ISSUE TITLE
Very interresting but can't understand the wiring !

### ISSUE THREAD

**Issue by davidmarli** [Savjee/home-energy-monitor#74]
Hi, I'm very interristing on building it, but I don't understand the wiring process ...

Would it be possible to have a complete scheme with resistors, sct-013 plug ... ?

On the blog, it's just 2 pictures and I see nothing ...

Thank you fo your help.

**Comment by Savjee** [comment]
The scheme is shown on the V1 blog post:
https://savjee.be/2019/07/Home-Energy-Monitor-ESP32-CT-Sensor-Emonlib/
