### ISSUE TITLE
Getting more Irms decimal points

### ISSUE THREAD

**Issue by Ganeshgng** [Savjee/home-energy-monitor#81]
Hi I am Trying to upload sensor data, current and voltage to mysql database. But I am struck. where
Irms value updating only two decimal places e.g X.XX, But I need X.XXXX, How to do it? I tried 
1. defining double Irms = emon.Irms/1.0000;
But when I try serial print & lcd print I can get the precision 
e.g Serial.print(emon.Irms, 5);

**Comment by Savjee** [comment]
Irms is measured in amps, and you're trying to detect 0.0001 amps? 
I'm afraid you'll never get that level of accuracy from a CT sensor.

Why do you need such high accuracy?
